# Generated by Django 5.2.15 on 2026-09-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('github', 'Github'), ('gitlab', 'GitLab'), ('gitea', 'Gitea'), ('oidc', 'OIDC')]),
        ),
    ]
